export const RESET_STATE = "RESET_STATE";

export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";

export const SET_SUB = "SET_SUB";
export const RESET_SUB = "RESET_SUB";

export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_USAGE = "SET_USAGE";
export const PATCH_ACCOUNT = "PATCH_ACCOUNT";
export const SET_DOMAINS = "SET_DOMAINS";
export const DELETE_DOMAIN = "DELETE_DOMAIN";
export const ADD_DOMAIN = "ADD_DOMAIN";
export const SET_CONSENTITEMS = "SET_CONSENTITEMS";
export const DELETE_CONSENTITEM = "DELETE_CONSENTITEM";
export const ADD_CONSENTITEM = "ADD_CONSENTITEM";
export const PATCH_CONSENTITEM = "PATCH_CONSENTITEM";
export const DECREMENT_CONTACTCOUNT = "DECREMENT_CONTACTCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

export const SET_CONTACTS = "SET_CONTACTS_LIST";
export const SET_SELECTEDCONSENTITEM = "SET_SELECTEDCONSENTITEM";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const RESET_CONTACTS = "RESET_CONTACTS_LIST";
